### ISSUE TITLE
nuget Tage Helper Package

### ISSUE THREAD

**Issue by weedkiller** [iamr8/R8#16]
Hello, can you separate the taghelpers and viewcomponents into their own nuget, they are very useful are you going to update the real estate project to .NET 5, or provide the DB scrip

**Comment by iamr8** [comment]
Hello 🙏🏽 

> can you separate the taghelpers and viewcomponents into their own nuget

I should check dependencies, if everything was ready, i'll make a separate nuget package for them.

> are you going to update the real estate project to .NET 5

Do you use that solution ? Unfortunately i don't have any plan to update that project! It will take much time. Maybe in future i do it !

**Comment by weedkiller** [comment]
yes .net 5 and now .NET 6 is the future
